
CREATE
  TABLE USER
  (
    ID                    INTEGER NOT NULL AUTO_INCREMENT ,
    EMAIL                 VARCHAR(35) NOT NULL,
    PASSWORD              VARCHAR(255) NOT NULL,
    AUTH_TOKEN            VARCHAR(255),
    VERIFIED      		  BOOLEAN,
    EMAIL_VERIFY_TOKEN 	  VARCHAR(255),
    CREATION_DATE_TIME    TIMESTAMP NOT NULL,
    LAST_CHANGE_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
  );
  
  
  CREATE
  TABLE COURSE
  (
    ID                    INTEGER NOT NULL AUTO_INCREMENT ,
    TITLE                 VARCHAR(255) NOT NULL,
    DESCRIPTION           VARCHAR(255),
    TYPE                  VARCHAR(35),
    DEFAULTTIME			  INTEGER
    CREATION_DATE_TIME    TIMESTAMP NOT NULL,
    LAST_CHANGE_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
  );
  
